# Generated by Django 5.2.4 on 2025-09-10 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_number', models.CharField(max_length=50)),
                ('bed_type', models.CharField(choices=[('general', 'General'), ('icu', 'ICU'), ('emergency', 'Emergency'), ('pediatric', 'Pediatric'), ('private', 'Private')], default='general', max_length=20)),
                ('is_occupied', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='hospitals.hospital')),
            ],
            options={
                'ordering': ['bed_type', 'bed_number'],
                'unique_together': {('hospital', 'bed_number')},
            },
        ),
    ]
