# Generated by Django 5.2.4 on 2025-11-13 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed',
            name='is_reserved_for_incident',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='bed',
            name='reserved_expiry_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bed',
            name='reserved_incident_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='bed',
            name='severity_level',
            field=models.CharField(db_index=True, default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='bed',
            name='is_occupied',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
